# Generated by Django 4.2.21 on 2026-04-02 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="icon",
        ),
    ]
