# Generated by Django 4.2.21 on 2026-04-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_remove_service_icon_remove_servicecategory_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
