# Generated by Django 4.2.21 on 2026-04-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
