# Generated by Django 4.2.21 on 2026-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicehero",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="وصف الصورة لتحسين SEO", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="servicehero",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
        migrations.AlterField(
            model_name="servicehero",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/"),
        ),
    ]
