# Generated by Django 4.2.21 on 2026-04-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_servicehero_alt_text_servicehero_video_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicehero",
            name="cta_link",
        ),
        migrations.RemoveField(
            model_name="servicehero",
            name="cta_text",
        ),
    ]
