# Generated by Django 4.2.21 on 2026-04-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_remove_servicehero_cta_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTrust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_years", models.CharField(max_length=20)),
                ("success_operations", models.CharField(max_length=20)),
                ("doctors_count", models.CharField(max_length=20)),
                ("satisfaction_rate", models.CharField(max_length=20)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust",
                        to="service.service",
                    ),
                ),
            ],
        ),
    ]
