# Generated by Django 4.2.21 on 2026-04-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0007_servicetrust"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProblemSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_title", models.CharField(max_length=255)),
                ("problem_description", models.TextField()),
                ("problem_image", models.ImageField(upload_to="service/problem/")),
                ("solution_title", models.CharField(max_length=255)),
                ("solution_description", models.TextField()),
                ("solution_image", models.ImageField(upload_to="service/solution/")),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_solution",
                        to="service.service",
                    ),
                ),
            ],
        ),
    ]
