# Generated by Django 4.2.21 on 2026-04-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0008_serviceproblemsolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemeta",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta",
                to="service.service",
            ),
        ),
        migrations.CreateModel(
            name="BeforeAfterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("before_image", models.ImageField(upload_to="before_after/")),
                ("after_image", models.ImageField(upload_to="before_after/")),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="before_after",
                        to="service.service",
                    ),
                ),
            ],
        ),
    ]
