# Generated by Django 4.2.21 on 2026-04-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0009_alter_servicemeta_service_beforeafterimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beforeafterimage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="before_after",
                to="service.service",
            ),
        ),
    ]
