# Generated by Django 4.2.21 on 2026-04-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="خطوات الإجراء", max_length=255)),
                (
                    "subtitle",
                    models.CharField(default="رحلة تحولك خطوة بخطوة", max_length=255),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "consultation_title",
                    models.CharField(default="استشارة مجانية", max_length=255),
                ),
                ("consultation_description", models.TextField()),
                (
                    "consultation_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preparation_title",
                    models.CharField(default="تحضير مسبق", max_length=255),
                ),
                ("preparation_description", models.TextField()),
                (
                    "preparation_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "procedure_title",
                    models.CharField(default="الإجراء", max_length=255),
                ),
                ("procedure_description", models.TextField()),
                (
                    "procedure_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "followup_title",
                    models.CharField(default="متابعة ونتائج", max_length=255),
                ),
                ("followup_description", models.TextField()),
                (
                    "followup_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure",
                        to="service.service",
                    ),
                ),
            ],
        ),
    ]
