# Generated by Django 4.2.21 on 2026-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0012_serviceprocedure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="خطوات الإجراء", max_length=200)),
                (
                    "subtitle",
                    models.CharField(default="رحلة تحولك خطوة بخطوة", max_length=200),
                ),
                (
                    "description",
                    models.TextField(default="نرافقك في كل مرحلة لضمان أفضل النتائج"),
                ),
                (
                    "consultation_title",
                    models.CharField(default="استشارة مجانية", max_length=100),
                ),
                (
                    "consultation_description",
                    models.TextField(default="تقييم شامل ووضع خطة مخصصة"),
                ),
                (
                    "preparation_title",
                    models.CharField(default="تحضير مسبق", max_length=100),
                ),
                (
                    "preparation_description",
                    models.TextField(default="فحوصات طبية وتجهيز المنطقة"),
                ),
                (
                    "procedure_title",
                    models.CharField(default="الإجراء", max_length=100),
                ),
                (
                    "procedure_description",
                    models.TextField(default="نحت الجسم باستخدام أحدث التقنيات"),
                ),
                (
                    "followup_title",
                    models.CharField(default="متابعة ونتائج", max_length=100),
                ),
                (
                    "followup_description",
                    models.TextField(default="رعاية متكاملة ونتائج مذهلة"),
                ),
            ],
        ),
    ]
