# Generated by Django 4.2.21 on 2026-04-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0013_proceduremodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceduremodule",
            name="service",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedure_module",
                to="service.service",
            ),
            preserve_default=False,
        ),
    ]
