# Generated by Django 4.2.21 on 2026-04-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0014_proceduremodule_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overviewcandidate",
            name="overview",
        ),
        migrations.RemoveField(
            model_name="packagefeature",
            name="package",
        ),
        migrations.RemoveField(
            model_name="pricingpackage",
            name="pricing",
        ),
        migrations.RemoveField(
            model_name="processstep",
            name="process",
        ),
        migrations.RemoveField(
            model_name="relatedservice",
            name="related",
        ),
        migrations.RemoveField(
            model_name="relatedservice",
            name="service",
        ),
        migrations.RemoveField(
            model_name="resulttimeline",
            name="result",
        ),
        migrations.RemoveField(
            model_name="servicemeta",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceoverview",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicepricing",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceprocess",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceresult",
            name="service",
        ),
        migrations.AddField(
            model_name="servicehero",
            name="cta_text",
            field=models.CharField(default="احجزي استشارتك المجانية", max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="consultation_description",
            field=models.TextField(default="تقييم شامل ووضع خطة مخصصة"),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="consultation_duration",
            field=models.CharField(default="30-45 دقيقة", max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="followup_description",
            field=models.TextField(default="رعاية متكاملة ونتائج مذهلة"),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="followup_duration",
            field=models.CharField(default="متابعة مستمرة", max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="preparation_description",
            field=models.TextField(default="فحوصات طبية وتجهيز المنطقة"),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="preparation_duration",
            field=models.CharField(default="15-30 دقيقة", max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="procedure_description",
            field=models.TextField(default="نحت الجسم باستخدام أحدث التقنيات"),
        ),
        migrations.AlterField(
            model_name="serviceprocedure",
            name="procedure_duration",
            field=models.CharField(default="60-180 دقيقة", max_length=100),
        ),
        migrations.AlterField(
            model_name="servicetrust",
            name="doctors_count",
            field=models.CharField(default="+20", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicetrust",
            name="experience_years",
            field=models.CharField(default="+10", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicetrust",
            name="satisfaction_rate",
            field=models.CharField(default="98%", max_length=20),
        ),
        migrations.AlterField(
            model_name="servicetrust",
            name="success_operations",
            field=models.CharField(default="+500", max_length=20),
        ),
        migrations.DeleteModel(
            name="OverviewBenefit",
        ),
        migrations.DeleteModel(
            name="OverviewCandidate",
        ),
        migrations.DeleteModel(
            name="PackageFeature",
        ),
        migrations.DeleteModel(
            name="PricingPackage",
        ),
        migrations.DeleteModel(
            name="ProcessStep",
        ),
        migrations.DeleteModel(
            name="RelatedService",
        ),
        migrations.DeleteModel(
            name="ResultTimeline",
        ),
        migrations.DeleteModel(
            name="ServiceMeta",
        ),
        migrations.DeleteModel(
            name="ServiceOverview",
        ),
        migrations.DeleteModel(
            name="ServicePricing",
        ),
        migrations.DeleteModel(
            name="ServiceProcess",
        ),
        migrations.DeleteModel(
            name="ServiceResult",
        ),
    ]
