# Generated by Django 4.2.21 on 2026-04-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0015_remove_overviewcandidate_overview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(upload_to="doctor/"),
        ),
    ]
