# Generated by Django 4.2.21 on 2026-04-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0016_alter_doctor_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprocedure",
            name="consultation_icon",
            field=models.CharField(blank=True, default="Users", max_length=50),
        ),
        migrations.AddField(
            model_name="serviceprocedure",
            name="followup_icon",
            field=models.CharField(blank=True, default="Heart", max_length=50),
        ),
        migrations.AddField(
            model_name="serviceprocedure",
            name="preparation_icon",
            field=models.CharField(blank=True, default="Shield", max_length=50),
        ),
        migrations.AddField(
            model_name="serviceprocedure",
            name="procedure_icon",
            field=models.CharField(blank=True, default="Sparkles", max_length=50),
        ),
        migrations.AlterField(
            model_name="serviceproblemsolution",
            name="problem_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="service/problem/"
            ),
        ),
        migrations.AlterField(
            model_name="serviceproblemsolution",
            name="solution_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="service/solution/"
            ),
        ),
    ]
