# Generated by Django 4.2.21 on 2026-04-06 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0017_serviceprocedure_consultation_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="consultation_icon",
        ),
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="description",
        ),
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="followup_icon",
        ),
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="preparation_icon",
        ),
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="procedure_icon",
        ),
    ]
