# Generated by Django 4.2.21 on 2026-04-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0018_remove_serviceprocedure_consultation_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_title", models.CharField(default="نتائج فورية", max_length=255)),
                (
                    "main_subtitle",
                    models.CharField(
                        default="ترى الفرق مباشرة بعد الجلسة", max_length=255
                    ),
                ),
                ("safety_title", models.CharField(default="آمن تماماً", max_length=255)),
                ("safety_description", models.TextField(default="تقنيات معتمدة دولياً")),
                (
                    "recovery_title",
                    models.CharField(default="تعافي سريع", max_length=255),
                ),
                (
                    "recovery_description",
                    models.TextField(default="عودي لحياتك الطبيعية خلال أيام"),
                ),
                ("care_title", models.CharField(default="رعاية شاملة", max_length=255)),
                (
                    "care_description",
                    models.TextField(default="متابعة مستمرة بعد الإجراء"),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature",
                        to="service.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="خطوات الإجراء", max_length=200)),
                (
                    "subtitle",
                    models.CharField(default="رحلة تحولك خطوة بخطوة", max_length=200),
                ),
                (
                    "description",
                    models.TextField(default="نرافقك في كل مرحلة لضمان أفضل النتائج"),
                ),
                (
                    "consultation_title",
                    models.CharField(default="استشارة مجانية", max_length=100),
                ),
                (
                    "consultation_description",
                    models.TextField(default="تقييم شامل ووضع خطة مخصصة"),
                ),
                (
                    "preparation_title",
                    models.CharField(default="تحضير مسبق", max_length=100),
                ),
                (
                    "preparation_description",
                    models.TextField(default="فحوصات طبية وتجهيز المنطقة"),
                ),
                (
                    "procedure_title",
                    models.CharField(default="الإجراء", max_length=100),
                ),
                (
                    "procedure_description",
                    models.TextField(default="نحت الجسم باستخدام أحدث التقنيات"),
                ),
                (
                    "followup_title",
                    models.CharField(default="متابعة ونتائج", max_length=100),
                ),
                (
                    "followup_description",
                    models.TextField(default="رعاية متكاملة ونتائج مذهلة"),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_steps",
                        to="service.service",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="serviceprocedure",
            name="service",
        ),
        migrations.DeleteModel(
            name="ProcedureModule",
        ),
        migrations.DeleteModel(
            name="ServiceProcedure",
        ),
    ]
