# Generated by Django 4.2.21 on 2026-04-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service",
            "0019_feature_processsteps_remove_serviceprocedure_service_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processsteps",
            name="description",
        ),
        migrations.AlterField(
            model_name="processsteps",
            name="subtitle",
            field=models.CharField(
                default="نرافقك في كل مرحلة لضمان أفضل النتائج", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="processsteps",
            name="title",
            field=models.CharField(default="رحلة تحولك خطوة بخطوة", max_length=200),
        ),
    ]
