# Generated by Django 4.2.21 on 2026-04-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0020_remove_processsteps_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processsteps",
            name="consultation_duration",
            field=models.CharField(default="30-45 دقيقة", max_length=100),
        ),
        migrations.AddField(
            model_name="processsteps",
            name="followup_duration",
            field=models.CharField(default="متابعة مستمرة", max_length=100),
        ),
        migrations.AddField(
            model_name="processsteps",
            name="preparation_duration",
            field=models.CharField(default="15-30 دقيقة", max_length=100),
        ),
        migrations.AddField(
            model_name="processsteps",
            name="procedure_duration",
            field=models.CharField(default="60-180 دقيقة", max_length=100),
        ),
    ]
