# Generated by Django 6.0.3 on 2026-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0022_rename_main_title_feature_results_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
