# Generated by Django 6.0.3 on 2026-04-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0023_alter_service_description_alter_service_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(),
        ),
    ]
