# Generated by Django 4.2.21 on 2026-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service", "0022_rename_main_title_feature_results_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ("summary", models.TextField(verbose_name="الملخص")),
                ("content", models.TextField(verbose_name="المحتوى (HTML)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_services",
                    models.ManyToManyField(blank=True, to="service.service"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
