# Generated by Django 4.2.21 on 2026-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="alt_text",
            field=models.CharField(
                blank=True, help_text="وصف الصورة لتحسين SEO", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
    ]
