# Generated by Django 4.2.21 on 2026-04-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_remove_servicehero_cta_link_and_more"),
        ("home", "0003_siteinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("campaign", models.ManyToManyField(blank=True, to="home.campaign")),
            ],
        ),
        migrations.CreateModel(
            name="TrackedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_url", models.URLField(verbose_name="Base URL")),
                (
                    "generated_url",
                    models.URLField(blank=True, verbose_name="Generated URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.source",
                        verbose_name="Source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_status",
                    models.CharField(
                        choices=[
                            ("WT", "WT - Waiting"),
                            ("PC", "PC - Paid Consultation"),
                            ("PP", "PP - Paid Procedure"),
                            ("PB", "PB - Paid Both"),
                            ("RF", "RF - Refunded"),
                        ],
                        default="WT",
                        max_length=3,
                    ),
                ),
                (
                    "procedure_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WT", "WT - Waiting"),
                            ("AC", "AC - Accepted"),
                            ("RJ", "RJ - Rejected"),
                            ("PP", "PP - Postponed"),
                        ],
                        default="WT",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "M - Male"), ("F", "F - Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("patient_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("s", "s - service"), ("p", "p - package")],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.campaign",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="home.package",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="service.service",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.source",
                    ),
                ),
            ],
        ),
    ]
