# Generated by Django 4.2.21 on 2026-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_campaign_source_trackedlink_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="procedure_decision",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="procedure_status",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="item_type",
            field=models.CharField(
                choices=[("s", "s - service"), ("p", "p - package")], max_length=1
            ),
        ),
    ]
