# Generated by Django 4.2.21 on 2026-04-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_appointment_amount_remove_appointment_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="patient_name",
            new_name="name",
        ),
    ]
