# Generated by Django 4.2.21 on 2026-04-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rename_patient_name_appointment_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrackedLink",
        ),
    ]
