# Generated by Django 4.2.21 on 2026-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="description",
        ),
        migrations.AddField(
            model_name="device",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="المحتوى (HTML)"
            ),
        ),
    ]
